[tools]
bun = "latest"
python = "latest"
node = "latest"
uv = "latest"
ruby = "latest"
"gem:rails" = "latest"
luajit = "latest"
clang = "latest"
go = "latest"
dotnet = "latest"
"github:railwayapp/railpack" = "latest"
