[symlinks]
"brew/.Brewfile" = "/Users/austindelic/.config/brew/.Brewfile"
"btop/btop.conf" = "/Users/austindelic/.config/btop/btop.conf"
"eza/theme.yaml" = "/Users/austindelic/.config/eza/theme.yaml"
"gh/config.yml" = "/Users/austindelic/.config/gh/config.yml"
"gh/hosts.yml" = "/Users/austindelic/.config/gh/hosts.yml"
"ghostty/config" = "/Users/austindelic/.config/ghostty/config"
"ghostty/shaders/cursor_ripple.glsl" = "/Users/austindelic/.config/ghostty/shaders/cursor_ripple.glsl"
"ghostty/shaders/cursor_warp.glsl" = "/Users/austindelic/.config/ghostty/shaders/cursor_warp.glsl"
"glow/glow.yml" = "/Users/austindelic/.config/glow/glow.yml"
"karabiner/assets/complex_modifications/builtin_swap_f1_media.json" = "/Users/austindelic/.config/karabiner/assets/complex_modifications/builtin_swap_f1_media.json"
"karabiner/karabiner.json" = "/Users/austindelic/.config/karabiner/karabiner.json"
"lazygit/config.yml" = "/Users/austindelic/.config/lazygit/config.yml"
"mise/config.toml" = "/Users/austindelic/.config/mise/config.toml"
"neovide/config.toml" = "/Users/austindelic/.config/neovide/config.toml"
"nvim/.gitignore" = "/Users/austindelic/.config/nvim/.gitignore"
"nvim/.neoconf.json" = "/Users/austindelic/.config/nvim/.neoconf.json"
"nvim/LICENSE" = "/Users/austindelic/.config/nvim/LICENSE"
"nvim/README.md" = "/Users/austindelic/.config/nvim/README.md"
"nvim/init.lua" = "/Users/austindelic/.config/nvim/init.lua"
"nvim/lazyvim.json" = "/Users/austindelic/.config/nvim/lazyvim.json"
"nvim/lua/config/autocmds.lua" = "/Users/austindelic/.config/nvim/lua/config/autocmds.lua"
"nvim/lua/config/keymaps.lua" = "/Users/austindelic/.config/nvim/lua/config/keymaps.lua"
"nvim/lua/config/lazy.lua" = "/Users/austindelic/.config/nvim/lua/config/lazy.lua"
"nvim/lua/config/options.lua" = "/Users/austindelic/.config/nvim/lua/config/options.lua"
"nvim/lua/plugins/blink.lua" = "/Users/austindelic/.config/nvim/lua/plugins/blink.lua"
"nvim/lua/plugins/example.lua" = "/Users/austindelic/.config/nvim/lua/plugins/example.lua"
"nvim/lua/plugins/overseer.lua" = "/Users/austindelic/.config/nvim/lua/plugins/overseer.lua"
"nvim/lua/plugins/telescope_native.lua" = "/Users/austindelic/.config/nvim/lua/plugins/telescope_native.lua"
"nvim/lua/plugins/theme.lua" = "/Users/austindelic/.config/nvim/lua/plugins/theme.lua"
"nvim/stylua.toml" = "/Users/austindelic/.config/nvim/stylua.toml"
"opencode/opencode.json" = "/Users/austindelic/.config/opencode/opencode.json"
"p10k/config.zsh" = "/Users/austindelic/.config/p10k/config.zsh"
"posting/config.yaml" = "/Users/austindelic/.config/posting/config.yaml"
"serie/config.toml" = "/Users/austindelic/.config/serie/config.toml"
"stu/error.log" = "/Users/austindelic/.config/stu/error.log"
"tmux/tmux.conf" = "/Users/austindelic/.config/tmux/tmux.conf"
"vscode/settings.json" = "/Users/austindelic/Library/Application Support/Code/User/settings.json"
"wallpapers/.DS_Store" = "/Users/austindelic/.config/wallpapers/.DS_Store"
"wallpapers/dark/.DS_Store" = "/Users/austindelic/.config/wallpapers/dark/.DS_Store"
"wallpapers/dark/02. Green Lush.png" = "/Users/austindelic/.config/wallpapers/dark/02. Green Lush.png"
"wallpapers/dark/11. Green Lush.png" = "/Users/austindelic/.config/wallpapers/dark/11. Green Lush.png"
"wallpapers/dark/15. Gruvbox Retro.png" = "/Users/austindelic/.config/wallpapers/dark/15. Gruvbox Retro.png"
"wallpapers/dark/20. Graphite Mono.png" = "/Users/austindelic/.config/wallpapers/dark/20. Graphite Mono.png"
"wallpapers/dark/a_painting_of_flowers_and_a_glass_of_wine.jpg" = "/Users/austindelic/.config/wallpapers/dark/a_painting_of_flowers_and_a_glass_of_wine.jpg"
"wallpapers/dark/asci-art.png" = "/Users/austindelic/.config/wallpapers/dark/asci-art.png"
"wallpapers/dark/ascii_rgba.png" = "/Users/austindelic/.config/wallpapers/dark/ascii_rgba.png"
"wallpapers/dark/beach_pixel.jpg" = "/Users/austindelic/.config/wallpapers/dark/beach_pixel.jpg"
"wallpapers/dark/brighter.png" = "/Users/austindelic/.config/wallpapers/dark/brighter.png"
"wallpapers/dark/darker.png" = "/Users/austindelic/.config/wallpapers/dark/darker.png"
"wallpapers/dark/gruvbox_image40.png" = "/Users/austindelic/.config/wallpapers/dark/gruvbox_image40.png"
"wallpapers/dark/just-bright.png" = "/Users/austindelic/.config/wallpapers/dark/just-bright.png"
"wallpapers/dark/middle.png" = "/Users/austindelic/.config/wallpapers/dark/middle.png"
"wallpapers/dark/moon_pixel.png" = "/Users/austindelic/.config/wallpapers/dark/moon_pixel.png"
"wallpapers/dark/output.png" = "/Users/austindelic/.config/wallpapers/dark/output.png"
"wallpapers/dark/output_bak-ascii-art.png" = "/Users/austindelic/.config/wallpapers/dark/output_bak-ascii-art.png"
"wallpapers/dark/output_bak.png" = "/Users/austindelic/.config/wallpapers/dark/output_bak.png"
"wallpapers/dark/output_zoom27.png" = "/Users/austindelic/.config/wallpapers/dark/output_zoom27.png"
"wallpapers/dark/pastel-window.png" = "/Users/austindelic/.config/wallpapers/dark/pastel-window.png"
"wallpapers/dark/wallhaven-2y91km.png" = "/Users/austindelic/.config/wallpapers/dark/wallhaven-2y91km.png"
"wallpapers/dark/wallhaven-7j931e.png" = "/Users/austindelic/.config/wallpapers/dark/wallhaven-7j931e.png"
"wallpapers/dark/wallpaper.heic" = "/Users/austindelic/.config/wallpapers/dark/wallpaper.heic"
"wallpapers/dark/wallpaper.png" = "/Users/austindelic/.config/wallpapers/dark/wallpaper.png"
"wallpapers/light/.DS_Store" = "/Users/austindelic/.config/wallpapers/light/.DS_Store"
"wallpapers/light/03. Green Lush.png" = "/Users/austindelic/.config/wallpapers/light/03. Green Lush.png"
"wallpapers/light/Screenshot 2025-11-16 at 12.56.07 am.png" = "/Users/austindelic/.config/wallpapers/light/Screenshot 2025-11-16 at 12.56.07 am.png"
"wallpapers/light/a_painting_of_a_garden_with_a_house_and_trees.jpeg" = "/Users/austindelic/.config/wallpapers/light/a_painting_of_a_garden_with_a_house_and_trees.jpeg"
"wallpapers/light/ocean_with_cloud.png" = "/Users/austindelic/.config/wallpapers/light/ocean_with_cloud.png"
"wallpapers/light/ship_blue_painting.png" = "/Users/austindelic/.config/wallpapers/light/ship_blue_painting.png"
"yazi/flavors/monokai-vibrant.yazi/LICENSE" = "/Users/austindelic/.config/yazi/flavors/monokai-vibrant.yazi/LICENSE"
"yazi/flavors/monokai-vibrant.yazi/LICENSE-tmtheme" = "/Users/austindelic/.config/yazi/flavors/monokai-vibrant.yazi/LICENSE-tmtheme"
"yazi/flavors/monokai-vibrant.yazi/README.md" = "/Users/austindelic/.config/yazi/flavors/monokai-vibrant.yazi/README.md"
"yazi/flavors/monokai-vibrant.yazi/flavor.toml" = "/Users/austindelic/.config/yazi/flavors/monokai-vibrant.yazi/flavor.toml"
"yazi/flavors/monokai-vibrant.yazi/preview.png" = "/Users/austindelic/.config/yazi/flavors/monokai-vibrant.yazi/preview.png"
"yazi/flavors/monokai-vibrant.yazi/tmtheme.xml" = "/Users/austindelic/.config/yazi/flavors/monokai-vibrant.yazi/tmtheme.xml"
"yazi/package.toml" = "/Users/austindelic/.config/yazi/package.toml"
"yazi/theme.toml" = "/Users/austindelic/.config/yazi/theme.toml"
"yazi/yazi.toml" = "/Users/austindelic/.config/yazi/yazi.toml"
"zed/keymap.json" = "/Users/austindelic/.config/zed/keymap.json"
"zed/settings.json" = "/Users/austindelic/.config/zed/settings.json"
"zed/tasks.json" = "/Users/austindelic/.config/zed/tasks.json"
"zsh/.hushlogin" = "/Users/austindelic/.hushlogin"
"zsh/.zshenv" = "/Users/austindelic/.zshenv"
"zsh/config/.p10k.zsh" = "/Users/austindelic/.config/zsh/.p10k.zsh"
"zsh/config/.zfunctions/is-macos" = "/Users/austindelic/.config/zsh/.zfunctions/is-macos"
"zsh/config/.zsh_history" = "/Users/austindelic/.config/zsh/.zsh_history"
"zsh/config/.zsh_plugins.txt" = "/Users/austindelic/.config/zsh/.zsh_plugins.txt"
"zsh/config/.zsh_plugins.zsh" = "/Users/austindelic/.config/zsh/.zsh_plugins.zsh"
"zsh/config/.zsh_sessions/63E047F5-DF85-44F8-A373-761E67D30A2C.session" = "/Users/austindelic/.config/zsh/.zsh_sessions/63E047F5-DF85-44F8-A373-761E67D30A2C.session"
"zsh/config/.zsh_sessions/7B0529D5-033F-445E-BD40-D9893019D5BD.session" = "/Users/austindelic/.config/zsh/.zsh_sessions/7B0529D5-033F-445E-BD40-D9893019D5BD.session"
"zsh/config/.zsh_sessions/7CFA9EFC-6B14-4536-87A7-E2B99E7AFDC3.session" = "/Users/austindelic/.config/zsh/.zsh_sessions/7CFA9EFC-6B14-4536-87A7-E2B99E7AFDC3.session"
"zsh/config/.zsh_sessions/D90EE1CF-15BA-4E4A-BDA9-768A6D48F9E9.session" = "/Users/austindelic/.config/zsh/.zsh_sessions/D90EE1CF-15BA-4E4A-BDA9-768A6D48F9E9.session"
"zsh/config/.zsh_sessions/F0A39B98-CDC7-4722-9A00-D1C70000AAB0.session" = "/Users/austindelic/.config/zsh/.zsh_sessions/F0A39B98-CDC7-4722-9A00-D1C70000AAB0.session"
"zsh/config/.zsh_sessions/_expiration_check_timestamp" = "/Users/austindelic/.config/zsh/.zsh_sessions/_expiration_check_timestamp"
"zsh/config/.zshrc" = "/Users/austindelic/.config/zsh/.zshrc"
"zsh/config/.zshrc.d/.fzf-git.zsh" = "/Users/austindelic/.config/zsh/.zshrc.d/.fzf-git.zsh"
"zsh/config/.zshrc.d/activate.zsh" = "/Users/austindelic/.config/zsh/.zshrc.d/activate.zsh"
"zsh/config/.zshrc.d/aliases.zsh" = "/Users/austindelic/.config/zsh/.zshrc.d/aliases.zsh"
"zsh/config/.zshrc.d/history-substring-search.zsh" = "/Users/austindelic/.config/zsh/.zshrc.d/history-substring-search.zsh"
"zsh/config/.zshrc.d/zsh-vim.zsh" = "/Users/austindelic/.config/zsh/.zshrc.d/zsh-vim.zsh"
"zsh/config/.zstyles" = "/Users/austindelic/.config/zsh/.zstyles"

[templates]
