[helpers]

[default]
depends = []

[default.files]
nvim = "~/.config/nvim/"
btop = "~/.config/btop/"
eza = "~/.config/eza/"
brew = "~/.config/brew"
lazygit = "~/.config/lazygit/"
yazi = "~/.config/yazi/"
"zsh/config" = "~/.config/zsh"
"zsh/.zshenv" = "~/.zshenv"
"zsh/.hushlogin" = "~/.hushlogin"
p10k = "~/.config/p10k"
tmux = "~/.config/tmux"
ghostty = "~/.config/ghostty"
vscode = "~/Library/Application Support/Code/User"
karabiner = "~/.config/karabiner"
neovide = "~/.config/neovide"
wallpapers = "~/.config/wallpapers"
spicetify = "~/.config/spicetify"
mise = "~/.config/mise"
posting = "~/.config/posting"
stu = "~/.config/stu"
opencode = "~/.config/opencode"
gh = "~/.config/gh"
glow = "~/.config/glow"
zed = "~/.config/zed"
[default.variables]

[settings]
default_target_type = "automatic"
